---
- hosts: local
  vars:
    base_rsyslogd_custom_init: true
    composer_path_env: true
    composer_home_path: /opt/composer
    nullmailer_remotes:
      - 127.0.0.1 smtp --port=1025
    drush_add_system_launcher: true

  roles: 
    - { role: drunomics.base, tags: base }
    - { role: drunomics.ssh, tags: ssh }
    - { role: drunomics.lamp, tags: lamp }
    - { role: drunomics.nullmailer, tags: nullmailer }
    - { role: drunomics.maildev-apache, tags: maildev }
    - { role: kosssi.composer, tags: composer }
    - { role: drunomics.drush, tags: drush }

  tasks:
    - name: Execute provision script.
      shell: |
        {%- for command in provision_script -%}
          {{ command }}
        {%- endfor -%}
      when: provision_script is defined
      tags: provision-script
