---
- hosts: local
  roles: 
    - { role: drunomics.base, tags: base }
    - { role: drunomics.ssh, tags: ssh }
    - { role: drunomics.lamp, tags: lamp }
    - { role: drunomics.nullmailer, tags: nullmailer }
    - { role: drunomics.maildev-apache, tags: maildev }
