---
- hosts: local
  vars:
    - composer_path_env: true
  roles: 
    - { role: drunomics.base, tags: base }
    - { role: drunomics.ssh, tags: ssh }
    - { role: drunomics.lamp, tags: lamp }
    - { role: drunomics.nullmailer, tags: nullmailer }
    - { role: drunomics.maildev-apache, tags: maildev }
    - role: drunomics.drush
      tags: drush
      composer_register_global_bin: true
