---

- src: https://github.com/drunomics/ansible-role-memcached
  name: drunomics.memcached

  # Make sure to use the latest version.
- src: https://github.com/drunomics/ansible-role-php
  name: drunomics.php
  version: master
